//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoomzGlobal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoomzGlobalEntities : DbContext
    {
        public BoomzGlobalEntities()
            : base("name=BoomzGlobalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advertisement_T> Advertisement_T { get; set; }
        public DbSet<Category_T> Category_T { get; set; }
        public DbSet<City_T> City_T { get; set; }
        public DbSet<Company_T> Company_T { get; set; }
        public DbSet<Company_Package_T> Company_Package_T { get; set; }
        public DbSet<Country_T> Country_T { get; set; }
        public DbSet<Franchise_T> Franchise_T { get; set; }
        public DbSet<Package_T> Package_T { get; set; }
        public DbSet<SubCategory_T> SubCategory_T { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
