//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoomzGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_T
    {
        public City_T()
        {
            this.Company_T = new HashSet<Company_T>();
            this.Franchise_T = new HashSet<Franchise_T>();
            this.Package_T = new HashSet<Package_T>();
        }
    
        public int CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string City { get; set; }
    
        public virtual Country_T Country_T { get; set; }
        public virtual ICollection<Company_T> Company_T { get; set; }
        public virtual ICollection<Franchise_T> Franchise_T { get; set; }
        public virtual ICollection<Package_T> Package_T { get; set; }
    }
}
