//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoomzGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Package_T
    {
        public int CompanyPackageID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> FranchiseID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    
        public virtual Company_T Company_T { get; set; }
        public virtual Franchise_T Franchise_T { get; set; }
        public virtual Package_T Package_T { get; set; }
    }
}
