//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoomzGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_T
    {
        public Country_T()
        {
            this.City_T = new HashSet<City_T>();
            this.Company_T = new HashSet<Company_T>();
            this.Franchise_T = new HashSet<Franchise_T>();
        }
    
        public int CountryID { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<City_T> City_T { get; set; }
        public virtual ICollection<Company_T> Company_T { get; set; }
        public virtual ICollection<Franchise_T> Franchise_T { get; set; }
    }
}
