//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoomzGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_T
    {
        public Package_T()
        {
            this.Company_Package_T = new HashSet<Company_Package_T>();
        }
    
        public int PackageID { get; set; }
        public Nullable<int> FranchiseID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Package { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    
        public virtual City_T City_T { get; set; }
        public virtual ICollection<Company_Package_T> Company_Package_T { get; set; }
        public virtual Franchise_T Franchise_T { get; set; }
    }
}
