//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoomzGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory_T
    {
        public SubCategory_T()
        {
            this.Company_T = new HashSet<Company_T>();
        }
    
        public int SubCategoryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string SubCategory { get; set; }
    
        public virtual Category_T Category_T { get; set; }
        public virtual ICollection<Company_T> Company_T { get; set; }
    }
}
